#!/usr/bin/env python3

import os
import sys

def tamanho_legivel(size):
    for unit in ['bytes', 'KB', 'MB', 'GB', 'TB']:
        if size < 1024:
            return f"{size:.2f} {unit}"
        size /= 1024

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Uso: size <ficheiro>")
    else:
        caminho = sys.argv[1]
        try:
            tamanho = os.path.getsize(caminho)
            print(tamanho_legivel(tamanho))
        except FileNotFoundError:
            print(f"Erro: ficheiro '{caminho}' não encontrado.")
